on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  block_label:
    runs-on: ubuntu-latest
    name: Check for 'breaking' label on non-breaking base ref
    steps:
      - uses: rofe/github-label-wip-action@v1.0.1
        with:
          label: breaking
          allowed_base: breaking-.*
